id: I2D7ED3FD
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T22:40:18+00:00'
last_modified: '2022-06-07T17:43:46.406672+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG03704
  title: རྟགས་རིགས་ཀྱི་རྣམ་བཞག་ཉུང་གསལ་ལེགས་བཤད་གསེར་གྱི་ཕྲེང་མཛེས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    037B:
      image_group_id: I00KG03786
      title: ''
      total_pages: 164
      order: 1
      base_file: 037B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
