id: P003120
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG03704
  title: རྟགས་རིགས་ཀྱི་རྣམ་བཞག་ཉུང་གསལ་ལེགས་བཤད་གསེར་གྱི་ཕྲེང་མཛེས།
  author: ''
  volumes:
    8df1711a962841ef80c9c27b28dbc580:
      image_group_id: I00KG03786
      title: ''
      volume_number: 1
      total_pages: 164
